name: Update Albums Data

on:
  workflow_dispatch:
    inputs:
      albums_data:
        description: 'Albums data in JSON format'
        required: true
        type: string
      commit_message:
        description: 'Commit message'
        required: false
        default: 'Update albums data from admin interface'
        type: string

jobs:
  update-albums:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Update albums.js file
      run: |
        echo '${{ github.event.inputs.albums_data }}' > client/src/data/albums.js
        
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add client/src/data/albums.js
        git commit -m "${{ github.event.inputs.commit_message }}" || exit 0
        git push