name: Update Albums Data

on:
  repository_dispatch:
    types: [update-albums]

jobs:
  update-albums:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Update albums.js file
      run: |
        echo "Updating albums.js with new data..."
        # Create the albums.js file using a here document to avoid quote issues
        cat > client/src/data/albums.js << 'EOF'
        ${{ github.event.client_payload.albums_data }}
        EOF
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add client/src/data/albums.js
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update albums data from admin interface

          - Updated by: ${{ github.event.client_payload.updated_by || 'Admin' }}
          - Timestamp: ${{ github.event.client_payload.timestamp }}
          - Albums count: ${{ github.event.client_payload.albums_count }}"
          git push
        fi
        
    - name: Trigger GitHub Pages rebuild
      run: |
        echo "Albums data updated successfully!"
        echo "GitHub Pages will rebuild automatically."
